create table if not exists tokens (
  id bigint generated by default as identity primary key,
  address text not null,
  symbol text,
  name text,
  chain text not null,
  price_usd numeric,
  liquidity_usd numeric,
  volume_5m_usd numeric,
  volume_1h_usd numeric,
  market_cap_usd numeric,
  created_at timestamptz default now()
);

create table if not exists agent_runs (
  id bigint generated by default as identity primary key,
  token_id bigint references tokens(id),
  agent_name text not null,
  status text not null,
  score numeric,
  note text,
  data jsonb,
  created_at timestamptz default now()
);

create table if not exists paper_trades (
  id bigint generated by default as identity primary key,
  address text not null,
  chain text not null,
  action text not null,
  amount_usd numeric not null,
  entry_price numeric,
  exit_price numeric,
  pnl_usd numeric,
  pnl_pct numeric,
  reason text,
  created_at timestamptz default now()
);